[ISOs]
path = __SAMBA_DIR__/__SAMBA_SHARE_ISO__
browseable = yes
valid users = __SAMBA_USER__
write list = __SAMBA_USER__
guest ok = no
create mask = 0755
directory mask = 0755

[Clonezilla]
path = __SAMBA_DIR__/__SAMBA_SHARE_CLONEZILLA__
browseable = yes
valid users = __SAMBA_USER__
write list = __SAMBA_USER__
guest ok = no
create mask = 0755
directory mask = 0755

[Recursos_Compartidos]
path = __SAMBA_DIR__/__SAMBA_SHARE_RECURSOS_COMPARTIDOS__
browseable = yes
valid users = __SAMBA_USER__, anonimo
write list = __SAMBA_USER__
guest ok = no
create mask = 0755
directory mask = 0755