[global]
workgroup = WORKGROUP
netbios name = DEPLOYSERVER
server string = Servidor de Imágenes
security = user
map to guest = never
log file = /var/log/samba/log.%m
max log size = 1000
logging = file
panic action = /usr/share/samba/panic-action %d

[ISOs]
path = __SAMBA_DIR__/__SAMBA_SHARE_ISO__
browseable = yes
valid users = __SAMBA_USER__
write list = __SAMBA_USER__
guest ok = no
create mask = 0755
directory mask = 0755

[Clonezilla]
path = __SAMBA_DIR__/__SAMBA_SHARE_CLONEZILLA__
browseable = yes
valid users = __SAMBA_USER__
write list = __SAMBA_USER__
guest ok = no
create mask = 0755
directory mask = 0755

[Recursos_Compartidos]
path = __SAMBA_DIR__/__SAMBA_SHARE_RECURSOS_COMPARTIDOS__
browseable = yes
valid users = __SAMBA_USER__, anonimo
write list = __SAMBA_USER__
guest ok = no
create mask = 0755
directory mask = 0755
