server {
    listen 80;
    server_name servidorimagen.__DOMAIN__ webmin.__DOMAIN__ iventoy.__DOMAIN__;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name servidorimagen.__DOMAIN__;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    proxy_pass_header Set-Cookie;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = /auth/check {
        internal;
        proxy_pass http://localhost:3000/auth/check;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header Cookie $http_cookie;
    }

    location / {
        auth_request /auth/check;
        error_page 401 = @login_redirect;
        root /var/www/html/portal;
        index home.html;
        try_files $uri $uri/ =404;
    }

    location /login {
        proxy_pass http://localhost:3000/login;
        proxy_set_header Host $host;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Content-Type $content_type;
        proxy_pass_header Set-Cookie;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location @login_redirect {
        return 302 https://servidorimagen.__DOMAIN__/login?redirect=$scheme://$host$request_uri;
    }

    location /css/ {
        root /var/www/html/portal;
    }

    location /img/ {
        root /var/www/html/portal;
    }

    location /js/ {
        root /var/www/html/portal;
    }
}

server {
    listen 443 ssl;
    server_name webmin.__DOMAIN__;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location = /auth/check {
        internal;
        proxy_pass http://localhost:3000/auth/check;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Cookie $http_cookie;
    }

    location / {
        auth_request /auth/check;
        error_page 401 = @login_redirect;
        proxy_pass https://localhost:10000/;
        proxy_ssl_verify off;
        proxy_set_header Host $host;
    }

    location @login_redirect {
        return 302 https://servidorimagen.__DOMAIN__/login?redirect=$scheme://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name iventoy.__DOMAIN__;

    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location = /auth/check {
        internal;
        proxy_pass http://localhost:3000/auth/check;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Cookie $http_cookie;
    }

    location / {
        auth_request /auth/check;
        error_page 401 = @login_redirect;
        proxy_pass http://localhost:26000/;
        proxy_set_header Host $host;
    }

    location @login_redirect {
        return 302 https://servidorimagen.__DOMAIN__/login?redirect=$scheme://$host$request_uri;
    }
}